#!/bin/bash
# /etc/init.d/tomcats
# init script for all tomcats.
# generated by 'tomcat enable boot-start'.
#
# chkconfig: 2345 90 60
# description: Start all tomcat
#

ERROR=0
#JAVA_HOME=/usr/java/latest
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.4.11-1.el7_7.x86_64
PATH=$JAVA_HOME/bin:$PATH

case "$1" in
start)

echo $"Starting tomcats"

cd /opt/tomcats
SERVERS=$(ls | cut -d" " -f2)

for server in $SERVERS
do

sh /opt/tomcats/$server/bin/tomcat.sh start

done

 ;;

stop)

echo $"Stopping tomcats"

cd /opt/tomcats
SERVERS=$(ls | cut -d" " -f2)

for server in $SERVERS
do

sh /opt/tomcats/$server/bin/tomcat.sh stop

done

;;

restart)

cd /opt/tomcats
SERVERS=$(ls | cut -d" " -f2)

for server in $SERVERS
do

sh /opt/tomcats/$server/bin/tomcat.sh restart

done

 ;;

status)

cd /opt/tomcats
SERVERS=$(ls | cut -d" " -f2)

for server in $SERVERS
do

sh /opt/tomcats/$server/bin/tomcat.sh status

done

 ;;

*)

  echo $"Usage: $0 (start|stop|restart|status)"

exit 1

 ;;

esac

exit $ERROR
